<?xml version="1.0" encoding="utf-8"?><Database Name="CmsLite" Class="PagesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tserver;Initial Catalog=CmsLite;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CmsLiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Pages">
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.PageComposition" Member="PageCompositions">
    <Type Name="PageComposition">
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageCompositePartId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsList" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.PageEditors" Member="PageEditors">
    <Type Name="PageEditor">
      <Column Name="PageEditorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageEditor" Member="PageEditor1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Editor" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.PagePartComposition" Member="PagePartCompositions">
    <Type Name="PagePartComposition">
      <Column Name="PageCompositeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageEditor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Data" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.PageParts" Member="PageParts">
    <Type Name="PagePart">
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartName" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PartType" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PartCompositeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>